# Declarative icon catalog: background + semantic glyph + material defaults.
DEFAULT_MATERIAL={"material":"glass","specular":"automatic","refraction":0.045,"translucency":0.78,"shadow":0.055}
ICON_SPECS={
    'skeuo_phone': ({'type': 'solid', 'colors': ['#28c85c']}, 'phone', DEFAULT_MATERIAL),
    'skeuo_messages': ({'type': 'solid', 'colors': ['#28c85c']}, 'messages', DEFAULT_MATERIAL),
    'skeuo_camera': ({'type': 'solid', 'colors': ['#8f969e']}, 'camera', DEFAULT_MATERIAL),
    'skeuo_photos': ({'type': 'solid', 'colors': ['#f0f2f5']}, 'photos', DEFAULT_MATERIAL),
    'skeuo_settings': ({'type': 'solid', 'colors': ['#69727d']}, 'settings', DEFAULT_MATERIAL),
    'skeuo_mail': ({'type': 'solid', 'colors': ['#1989f5']}, 'mail', DEFAULT_MATERIAL),
    'skeuo_gmail': ({'type': 'solid', 'colors': ['#f0f2f5']}, 'gmail', DEFAULT_MATERIAL),
    'skeuo_maps': ({'type': 'solid', 'colors': ['#6ebf61']}, 'maps', DEFAULT_MATERIAL),
    'skeuo_google_maps': ({'type': 'solid', 'colors': ['#60b85e']}, 'google_maps', DEFAULT_MATERIAL),
    'skeuo_clock': ({'type': 'solid', 'colors': ['#1d1d20']}, 'clock', DEFAULT_MATERIAL),
    'skeuo_weather': ({'type': 'solid', 'colors': ['#1989f5']}, 'weather', DEFAULT_MATERIAL),
    'skeuo_notes': ({'type': 'solid', 'colors': ['#ffcc30']}, 'notes', DEFAULT_MATERIAL),
    'skeuo_calendar': ({'type': 'solid', 'colors': ['#f7f7f9']}, 'calendar', DEFAULT_MATERIAL),
    'skeuo_appstore': ({'type': 'solid', 'colors': ['#1788f5']}, 'appstore', DEFAULT_MATERIAL),
    'skeuo_facetime': ({'type': 'solid', 'colors': ['#28c85c']}, 'facetime', DEFAULT_MATERIAL),
    'skeuo_music': ({'type': 'solid', 'colors': ['#fa2d73']}, 'music', DEFAULT_MATERIAL),
    'skeuo_wallet': ({'type': 'solid', 'colors': ['#1d1d20']}, 'wallet', DEFAULT_MATERIAL),
    'skeuo_files': ({'type': 'solid', 'colors': ['#2d9cf5']}, 'files', DEFAULT_MATERIAL),
    'skeuo_calculator': ({'type': 'solid', 'colors': ['#29292d']}, 'calculator', DEFAULT_MATERIAL),
    'skeuo_health': ({'type': 'solid', 'colors': ['#f0f2f5']}, 'health', DEFAULT_MATERIAL),
    'skeuo_compass': ({'type': 'solid', 'colors': ['#30343b']}, 'compass', DEFAULT_MATERIAL),
    'skeuo_recorder': ({'type': 'solid', 'colors': ['#f7f7f9']}, 'recorder', DEFAULT_MATERIAL),
    'skeuo_chrome': ({'type': 'solid', 'colors': ['#f0f2f5']}, 'chrome', DEFAULT_MATERIAL),
    'skeuo_youtube': ({'type': 'solid', 'colors': ['#f31c24']}, 'youtube', DEFAULT_MATERIAL),
    'skeuo_revanced': ({'type': 'solid', 'colors': ['#15161a']}, 'revanced', DEFAULT_MATERIAL),
    'skeuo_telegram': ({'type': 'solid', 'colors': ['#2aabee']}, 'telegram', DEFAULT_MATERIAL),
    'skeuo_discord': ({'type': 'solid', 'colors': ['#5865f2']}, 'discord', DEFAULT_MATERIAL),
    'skeuo_instagram': ({'type': 'radial', 'colors': ['#5c35df', '#f02b78', '#ff9f45']}, 'instagram', DEFAULT_MATERIAL),
    'skeuo_twitter': ({'type': 'solid', 'colors': ['#1588d4']}, 'twitter', DEFAULT_MATERIAL),
    'skeuo_whatsapp': ({'type': 'solid', 'colors': ['#20bf5a']}, 'whatsapp', DEFAULT_MATERIAL),
    'skeuo_facebook': ({'type': 'solid', 'colors': ['#1877f2']}, 'facebook', DEFAULT_MATERIAL),
    'skeuo_snapchat': ({'type': 'solid', 'colors': ['#ffec1a']}, 'snapchat', DEFAULT_MATERIAL),
    'skeuo_reddit': ({'type': 'solid', 'colors': ['#ff4500']}, 'reddit', DEFAULT_MATERIAL),
    'skeuo_pinterest': ({'type': 'solid', 'colors': ['#e60023']}, 'pinterest', DEFAULT_MATERIAL),
    'skeuo_tiktok': ({'type': 'radial', 'colors': ['#08090c', '#171821', '#0d0d10']}, 'tiktok', DEFAULT_MATERIAL),
    'skeuo_slack': ({'type': 'radial', 'colors': ['#32113f', '#5b1b5e', '#1c6670']}, 'slack', DEFAULT_MATERIAL),
    'skeuo_spotify': ({'type': 'solid', 'colors': ['#1ed760']}, 'spotify', DEFAULT_MATERIAL),
    'skeuo_netflix': ({'type': 'solid', 'colors': ['#111114']}, 'netflix', DEFAULT_MATERIAL),
    'skeuo_amazon': ({'type': 'solid', 'colors': ['#e9c78e']}, 'amazon', DEFAULT_MATERIAL),
    'skeuo_uber': ({'type': 'solid', 'colors': ['#151619']}, 'uber', DEFAULT_MATERIAL),
    'skeuo_paypal': ({'type': 'solid', 'colors': ['#1f6fbd']}, 'paypal', DEFAULT_MATERIAL),
    'skeuo_venmo': ({'type': 'solid', 'colors': ['#328bd1']}, 'venmo', DEFAULT_MATERIAL),
    'skeuo_robinhood': ({'type': 'solid', 'colors': ['#62d84e']}, 'robinhood', DEFAULT_MATERIAL),
    'skeuo_strava': ({'type': 'solid', 'colors': ['#fc4c02']}, 'strava', DEFAULT_MATERIAL),
    'skeuo_zoom': ({'type': 'solid', 'colors': ['#2d8cff']}, 'zoom', DEFAULT_MATERIAL),
    'skeuo_shazam': ({'type': 'solid', 'colors': ['#1687f8']}, 'shazam', DEFAULT_MATERIAL),
    'skeuo_kaspi': ({'type': 'solid', 'colors': ['#f24034']}, 'kaspi', DEFAULT_MATERIAL),
    'skeuo_2gis': ({'type': 'solid', 'colors': ['#54b948']}, 'twogis', DEFAULT_MATERIAL),
    'skeuo_soundcloud': ({'type': 'solid', 'colors': ['#f45d0a']}, 'soundcloud', DEFAULT_MATERIAL),
    'skeuo_chatgpt': ({'type': 'radial', 'colors': ['#101614', '#17302a', '#0b1110']}, 'chatgpt', DEFAULT_MATERIAL),
    'skeuo_github': ({'type': 'solid', 'colors': ['#1f2328']}, 'github', DEFAULT_MATERIAL),
    'skeuo_steam': ({'type': 'solid', 'colors': ['#10385b']}, 'steam', DEFAULT_MATERIAL),
    'skeuo_gamehub': ({'type': 'radial', 'colors': ['#181a1e', '#2b3137', '#101215']}, 'gamehub', DEFAULT_MATERIAL),
    'skeuo_google_photos': ({'type': 'solid', 'colors': ['#f0f2f5']}, 'google_photos', DEFAULT_MATERIAL),
    'skeuo_google_keep': ({'type': 'solid', 'colors': ['#fbbc04']}, 'keep', DEFAULT_MATERIAL),
    'skeuo_google_calendar': ({'type': 'solid', 'colors': ['#f0f2f5']}, 'calendar', DEFAULT_MATERIAL),
    'skeuo_google_meet': ({'type': 'solid', 'colors': ['#21a366']}, 'meet', DEFAULT_MATERIAL),
    'skeuo_google_drive': ({'type': 'solid', 'colors': ['#f0f2f5']}, 'drive', DEFAULT_MATERIAL),
    'skeuo_google_docs': ({'type': 'solid', 'colors': ['#4285f4']}, 'docs', DEFAULT_MATERIAL),
    'skeuo_google_sheets': ({'type': 'solid', 'colors': ['#34a853']}, 'sheets', DEFAULT_MATERIAL),
    'skeuo_google_slides': ({'type': 'solid', 'colors': ['#fbbc04']}, 'slides', DEFAULT_MATERIAL),
    'skeuo_google_translate': ({'type': 'solid', 'colors': ['#4285f4']}, 'translate', DEFAULT_MATERIAL),
    'skeuo_google_search': ({'type': 'solid', 'colors': ['#f0f2f5']}, 'search', DEFAULT_MATERIAL),
    'skeuo_google_classroom': ({'type': 'solid', 'colors': ['#34a853']}, 'classroom', DEFAULT_MATERIAL),
    'skeuo_google_one': ({'type': 'solid', 'colors': ['#4f75d8']}, 'one', DEFAULT_MATERIAL),
    'skeuo_playstore': ({'type': 'solid', 'colors': ['#f0f2f5']}, 'playstore', DEFAULT_MATERIAL),
}
